from selenium import  webdriver 
import time
driver = webdriver.Chrome() 
driver.get('https://www.baidu.com/?tn=78000241_11_hao_pg')
time.sleep(1)
button1=driver.find_element_by_id('u1').find_element_by_name('tj_login')
button1.click()
time.sleep(1)
button2=driver.find_element_by_id('TANGRAM__PSP_10__footerULoginBtn')
button2.click()
time.sleep(0.5)
button3=driver.find_element_by_name('memberPass')
button3.click()
time.sleep(0.5)
user_name=driver.find_element_by_name('userName')
user_name.send_keys('15058305005')
password=driver.find_element_by_name('password')
password.send_keys('XHAvrilLavigne')
time.sleep(0.5)
button4=driver.find_element_by_id('TANGRAM__PSP_10__submit')
button4.click()